rbac:
  create: true

podSecurityPolicy:
  enabled: ${pod_security_policy_enable}

imagePullSecrets: ${image_pull_secrets}

## Define serviceAccount names for components. Defaults to component's fully qualified name.
##
serviceAccounts:
  alertmanager:
    create: false
  nodeExporter:
    create: false
  pushgateway:
    create: true
    name: ${pushgateway_service_account}
    annotations: ${pushgateway_service_account_annotations}
  server:
    create: true
    name: ${server_service_account}
    annotations: ${server_service_account_annotations}

## Monitors ConfigMap changes and POSTs to a URL
## Ref: https://github.com/jimmidyson/configmap-reload
##
configmapReload:
  prometheus:
    ## If false, the configmap-reload container will not be deployed
    ##
    enabled: true

    ## configmap-reload container name
    ##
    name: ${configmap_name}

    ## configmap-reload container image
    ##
    image:
      repository: ${configmap_image_repo}
      tag: ${configmap_image_tag}
      pullPolicy: ${configmap_image_pull_policy}

    ## Additional configmap-reload container arguments
    ##
    extraArgs: ${configmap_extra_args}
    ## Additional configmap-reload volume directories
    ##
    extraVolumeDirs: ${configmap_extra_args}


    ## Additional configmap-reload mounts
    ##
    extraConfigmapMounts: ${configmap_extra_volumes}
      # - name: prometheus-alerts
      #   mountPath: /etc/alerts.d
      #   subPath: ""
      #   configMap: prometheus-alerts
      #   readOnly: true

    ## configmap-reload resource requests and limits
    ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources: ${configmap_resources}

  alertmanager:
    enabled: false

# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:
# example adds prometheus-blackbox-exporter scrape config
extraScrapeConfigs: ${extra_scrape_configs}
  # - job_name: 'prometheus-blackbox-exporter'
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]
  #   static_configs:
  #     - targets:
  #       - https://example.com
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: prometheus-blackbox-exporter:9115

networkPolicy:
  ## Enable creation of NetworkPolicy resources.
  ##
  enabled: ${enable_network_policy}

# Disable "dependent" chart
kubeStateMetrics:
  ## If false, kube-state-metrics will not be installed
  ##
  enabled: false

# Use the standalone Node Exporter chart
nodeExporter:
  enabled: false

# Use the standalone Alertmanager chart
alertmanager:
  enabled: false
